### ISSUE TITLE
Add to CorrelationContext the configured header name

### ISSUE THREAD

**Issue by juchom** [stevejgordon/CorrelationId#11]
I have a class making http calls to an api and I'm injecting the ICorrelationContextAccessor.

It would be great if we could have a field to get the configured name of the header.

```
    _correlationContext.CorrelationContext.CorrelationId
    _correlationContext.CorrelationContext.CorrelationHeaderName
```

**Comment by kiapanahi** [comment]
You can simply inject `IOptions<CorrelationIdOptions>` and have access to `CorrelationIdOptions` properties.

```
private class SampleClass
{
    private readonly ICorrelationContextAccessor _correlationContext;
    private readonly CorrelationIdOptions _correlationidOptions;

    public SampleClass(ICorrelationContextAccessor correlationContext, IOptions<CorrelationIdOptions> correlationidOptionsAccessor)
    {
        _correlationContext = correlationContext;
        _correlationidOptions = correlationidOptionsAccessor.Value;
    }
}
```

**Comment by juchom** [comment]
Your solution works, but I think that the CorrelationContext should have it.

Acutally you can retrieve the CorrelationId, it would be great to know from where.

If @stevejgordon is ok with that, I can make a PR for this.

**Comment by stevejgordon** [comment]
Sorry for the delay. I have a lot of noise in my GitHub notifications and missed this entirely.

One advantage of IOptions is that you get updates if the config changes, although only if you store the IOptions<T> on your field, rather than the resolved Value.

If people would find it useful to have it on the Context, I'm happy to see what we can do (and accept a PR for it). As it's a context per request the config value should be safe to bake in at that point as the request is short lived.

**Comment by juchom** [comment]
Ok, I'm going to have a look at it and make a proposal!

**Comment by stevejgordon** [comment]
Closing as #12 has been merged. The plan is to release this as part of a 2.1.0 package at some time in the near future.

**Comment by stevejgordon** [comment]
@juchom I've pushed an RC package for 2.1 which includes your PR changes.

You should be able to add the RC package using `dotnet` add package CorrelationId --version 2.1.0-rc

I'll hopefully test this more fully over the next week or so and then do a final release after that.
